// Native Unity tests for the BARQ protocol codec.
// Golden vectors are generated by barq_control/test/test_protocol.py - the two test
// suites pin the SAME bytes (cross-language contract). Regenerate only together.
#include <string.h>

#include <unity.h>

#include "../../src/protocol.h"

using namespace barq;

static const uint8_t GOLD_CMD[] = {
    0xba, 0x51, 0x01, 0x01, 0x2a, 0x18, 0x00, 0x00, 0xf4, 0x01, 0x0c, 0xfe,
    0xe8, 0x03, 0x18, 0xfc, 0xdc, 0x05, 0x24, 0xfa, 0xd0, 0x07, 0x30, 0xf8,
    0x01, 0x00, 0xff, 0xff, 0x98, 0x08, 0x4f, 0xc5};
static const uint8_t GOLD_PING[] = {
    0xba, 0x51, 0x01, 0x03, 0x05, 0x04, 0xde, 0xad, 0xbe, 0xef, 0x3f, 0xa0};

void test_crc16_known_vector() {
  const uint8_t s[] = "123456789";
  TEST_ASSERT_EQUAL_HEX16(0x29B1, crc16_ccitt(s, 9));
}

void test_cmd_frame_matches_python_golden() {
  CmdPayload p;
  const int16_t mrad[12] = {0, 500, -500, 1000, -1000, 1500, -1500, 2000, -2000, 1, -1, 2200};
  memcpy(p.targets_mrad, mrad, sizeof(mrad));
  uint8_t out[64];
  const size_t n = make_frame(TYPE_CMD, 0x2A, reinterpret_cast<uint8_t*>(&p), sizeof(p), out);
  TEST_ASSERT_EQUAL_UINT32(sizeof(GOLD_CMD), n);
  TEST_ASSERT_EQUAL_HEX8_ARRAY(GOLD_CMD, out, n);
}

void test_ping_frame_matches_python_golden() {
  const uint8_t tok[] = {0xde, 0xad, 0xbe, 0xef};
  uint8_t out[16];
  const size_t n = make_frame(TYPE_PING, 5, tok, 4, out);
  TEST_ASSERT_EQUAL_UINT32(sizeof(GOLD_PING), n);
  TEST_ASSERT_EQUAL_HEX8_ARRAY(GOLD_PING, out, n);
}

void test_decoder_roundtrip_bytewise() {
  Decoder d;
  bool got = false;
  for (size_t i = 0; i < sizeof(GOLD_CMD); ++i) got = d.feed(GOLD_CMD[i]);
  TEST_ASSERT_TRUE(got);
  TEST_ASSERT_EQUAL_HEX8(TYPE_CMD, d.type());
  TEST_ASSERT_EQUAL_HEX8(0x2A, d.seq());
  TEST_ASSERT_EQUAL_UINT32(CMD_PAYLOAD_LEN, d.payload_len());
  CmdPayload p;
  memcpy(&p, d.payload(), sizeof(p));
  TEST_ASSERT_EQUAL_INT16(500, p.targets_mrad[1]);
  TEST_ASSERT_EQUAL_INT16(-2000, p.targets_mrad[8]);
  TEST_ASSERT_EQUAL_INT16(2200, p.targets_mrad[11]);
}

void test_decoder_rejects_corruption_then_resyncs() {
  uint8_t bad[sizeof(GOLD_CMD)];
  memcpy(bad, GOLD_CMD, sizeof(bad));
  bad[10] ^= 0xFF;
  Decoder d;
  bool got = false;
  for (size_t i = 0; i < sizeof(bad); ++i) got |= d.feed(bad[i]);
  TEST_ASSERT_FALSE(got);
  for (size_t i = 0; i < sizeof(GOLD_PING); ++i) got |= d.feed(GOLD_PING[i]);
  TEST_ASSERT_TRUE(got);
  TEST_ASSERT_EQUAL_HEX8(TYPE_PING, d.type());
}

void test_decoder_resyncs_on_garbage_prefix() {
  Decoder d;
  const uint8_t junk[] = {0x00, 0xba, 0x42, 0xba, 0x51, 0x07};  // traps incl. fake magic
  bool got = false;
  for (size_t i = 0; i < sizeof(junk); ++i) got |= d.feed(junk[i]);
  for (size_t i = 0; i < sizeof(GOLD_CMD); ++i) got |= d.feed(GOLD_CMD[i]);
  TEST_ASSERT_TRUE(got);
  TEST_ASSERT_EQUAL_HEX8(TYPE_CMD, d.type());
}

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_crc16_known_vector);
  RUN_TEST(test_cmd_frame_matches_python_golden);
  RUN_TEST(test_ping_frame_matches_python_golden);
  RUN_TEST(test_decoder_roundtrip_bytewise);
  RUN_TEST(test_decoder_rejects_corruption_then_resyncs);
  RUN_TEST(test_decoder_resyncs_on_garbage_prefix);
  return UNITY_END();
}
